<a href="https://colab.research.google.com/github/SuccessPear/PyTorch-for-Deep-Learning/blob/main/00_pytorch_fundamentals/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch fundamentals

In [1]:
print("Hello, I'm Cong")

Hello, I'm Cong


In [2]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [3]:
import torch
print(torch.__version__)

2.2.1+cu121


In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Introduction to Tensors

### Creating a tensor
PyTorch tensors are created using torch.tensor() = https://pytorch.org/docs/stable/generated/torch.tensor.html#torch.tensor

In [5]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
scalar.item()

7

In [8]:
# Vector
vector = torch.tensor([7,2])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10],
                       [11,12]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])

In [12]:
MATRIX.shape

torch.Size([3, 2])

In [13]:
MATRIX.ndim

2

In [14]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [15]:
TENSOR2 = torch.tensor([[[1,2,3]],
                        [[4,5,6]],
                        [[7,8,9]]])

In [16]:
TENSOR2.ndim

3

In [17]:
TENSOR2.shape

torch.Size([3, 1, 3])

### Random tensor

Why random tensor?

Random tensors are important beause the way may neural networks learn is that they start wwith tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`



In [18]:
# Create a random tensro of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1942, 0.5587, 0.8848, 0.7586],
        [0.1877, 0.4560, 0.1252, 0.6111],
        [0.2694, 0.6956, 0.6575, 0.2148]])

In [19]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [20]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))

In [21]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))

## Creating a range of tensors and tensor-like

In [23]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & Deep learning:
1. Tensors not right datatype (tensor.dtype)
2. Tensors not right shape    (tensor.shape)
3. Tensors not right device   (tensor.device)

In [25]:
# Float32 tentor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # What data type is the tensor
                               device=None, # What device is your tensor on
                               requires_grad=False) # Whether or not to trach gradients with this tensor
float_32_tensor

tensor([3., 6., 9.])

In [26]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [27]:
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [28]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [29]:
int_32_tensor = torch.tensor([3, 6, 8], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 8], dtype=torch.int32)

In [30]:
int_32_tensor * float_32_tensor

tensor([ 9., 36., 72.])

## Getting information from tensors

In [31]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.5213, 0.3878, 0.7821, 0.3652],
        [0.9709, 0.3668, 0.9736, 0.2823],
        [0.2847, 0.1452, 0.6762, 0.1297]])

In [32]:
# Find out details about some_tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.5213, 0.3878, 0.7821, 0.3652],
        [0.9709, 0.3668, 0.9736, 0.2823],
        [0.2847, 0.1452, 0.6762, 0.1297]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [33]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [34]:
# Multiply by 10
tensor * 10

tensor([10, 20, 30])

In [35]:
# Built in function
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [36]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equal: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equal: tensor([1, 4, 9])


In [37]:
# Matrix multiplication
%%time
torch.matmul(tensor, tensor)

CPU times: user 1.67 ms, sys: 118 µs, total: 1.78 ms
Wall time: 9.12 ms


tensor(14)

In [38]:
%%time
tensor @ tensor

CPU times: user 1.25 ms, sys: 45 µs, total: 1.3 ms
Wall time: 1.51 ms


tensor(14)

### Common error in pytorch: mitmatch size

In [39]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

In [40]:
tensor_B = torch.tensor([[7, 8],
                         [9, 10],
                         [11, 12]])

In [41]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issuses, we can manipulate the shape of one of our tensors using a **transpose**.
A **transpose** switches the axes or dimensions of a given tensor.

In [42]:
tensor_B

tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])

In [43]:
tensor_B.T

tensor([[ 7,  9, 11],
        [ 8, 10, 12]])

In [44]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

## Finding the min, max, mean, sum,...**văn bản in đậm**

In [45]:
# Create a tensor
x = torch.arange(0, 100, 10)

In [46]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [47]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [48]:
# Find the mean
torch.mean(x, dtype=torch.float32), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [49]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [50]:
# Find the position that has the minimum value
x.argmin()

tensor(0)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - remove all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - return a view  of the input with dimensions permuted (swapped) in a certain way

In [51]:
# Create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [52]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [53]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [54]:
# Changing z will change x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [55]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

## Squeeze and Unsqueeze

In [56]:
x_reshaped.shape

torch.Size([1, 9])

In [57]:
x_squeezed = x_reshaped.squeeze()

In [58]:
# torch.unsqueeze
print(f'Previous target: {x_squeezed}')
print(f'Previous shape: {x_squeezed.shape}')

x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f'New target: {x_unsqueezed}')
print(f'New shape: {x_unsqueezed.shape}')

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])
New target: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [59]:
# torch.permute - rearranges the dimensions of a tensor in a specify order
x_original = torch.rand(size=(224, 224, 3)) # height, width, channels

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shift 0->1, 1->2, 2->0

print(f'Previous shape: {x_original.shape}')
print(f'New shape: {x_permuted.shape}')

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with Numpy

In [60]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [61]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [68]:
x[:,:,1]

tensor([[2, 5, 8]])

## PyTorch tensors & Numpy

Numpy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in Pytorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> Numpy -> `torch.Tensor.numpy()`

In [72]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
# warning: when converting from numpy -> pytorch, pytorch reflect numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [71]:
array.dtype

dtype('float64')

In [73]:
# Change the value of array, what will this do to tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [74]:
# Tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [75]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility (trying to take random out of random)

How neural network works:

`Start with random numbers -> tensor operations -> update random numbres -> again -> ... ->`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**

In [79]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)


tensor([[0.3852, 0.6253, 0.6956, 0.6371],
        [0.5182, 0.6870, 0.2312, 0.9201],
        [0.1798, 0.6732, 0.2072, 0.6118]])
tensor([[0.5236, 0.7573, 0.1355, 0.1626],
        [0.9500, 0.4384, 0.0915, 0.5863],
        [0.5014, 0.0083, 0.1536, 0.7647]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [80]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computation)


### 1. Geting a GPU

1. Easiest - Using google colab for free (options to upgrade)
2. Use your own GPU - takes a little bit of setup and requres the investment of purchasing a GPU
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

Note for 2, 3 PyTorch: + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setting documentation

### 2. Check for GPU access with PyTorch

In [83]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

False

In [84]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [85]:
torch.cuda.device_count()

0

### 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computation

In [86]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [87]:
# Move tensor to GPU (if available)
tensor_on_device = tensor.to(device)
tensor_on_device

tensor([1, 2, 3])

### 4. Moving tensor back to the CPU

In [90]:
# If tensor is on GPU, can't transform it to NumPy
# Use Tensor.cpu() to copy the tensor to cpu first

tensor_back_on_cpu = tensor_on_device.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])